// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

interface NavDocumentData {}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

type PageDocumentDataSlicesSlice =
  | TimelineSlice
  | FormSlice
  | CardsSlice
  | SimpleTextSectionSlice
  | HeroSlice
  | ItemsMatrixSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = NavDocument | PageDocument;

/**
 * Item in *Cards → Default → Primary → cards*
 */
export interface CardsSliceDefaultPrimaryCardsItem {
  /**
   * Icon field in *Cards → Default → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Cards → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Cards → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * Heading field in *Cards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * cards field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryCardsItem>>;

  /**
   * Compact field in *Cards → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cards.default.primary.compact
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  compact: prismic.BooleanField;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Heading field in *Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * LinkText field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.linktext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  linktext: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Background field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background: prismic.ImageField<never>;

  /**
   * Logo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ItemsMatrix → Default → Primary → Tiles*
 */
export interface ItemsMatrixSliceDefaultPrimaryTilesItem {
  /**
   * background field in *ItemsMatrix → Default → Primary → Tiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.default.primary.tiles[].background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background: prismic.ImageField<never>;

  /**
   * label field in *ItemsMatrix → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.default.primary.tiles[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Popup content field in *ItemsMatrix → Default → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.default.primary.tiles[].popup_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  popup_content: prismic.RichTextField;
}

/**
 * Item in *ItemsMatrix → With Rich Text → Primary → Tiles*
 */
export interface ItemsMatrixSliceWithRichTextPrimaryTilesItem {
  /**
   * background field in *ItemsMatrix → With Rich Text → Primary → Tiles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.withRichText.primary.tiles[].background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background: prismic.ImageField<never>;

  /**
   * label field in *ItemsMatrix → With Rich Text → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.withRichText.primary.tiles[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Popup content field in *ItemsMatrix → With Rich Text → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.withRichText.primary.tiles[].popup_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  popup_content: prismic.RichTextField;

  /**
   * text field in *ItemsMatrix → With Rich Text → Primary → Tiles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.withRichText.primary.tiles[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *ItemsMatrix → Default → Primary*
 */
export interface ItemsMatrixSliceDefaultPrimary {
  /**
   * Heading field in *ItemsMatrix → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Tiles field in *ItemsMatrix → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.default.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tiles: prismic.GroupField<Simplify<ItemsMatrixSliceDefaultPrimaryTilesItem>>;
}

/**
 * Default variation for ItemsMatrix Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ItemsMatrixSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ItemsMatrixSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ItemsMatrix → With Rich Text → Primary*
 */
export interface ItemsMatrixSliceWithRichTextPrimary {
  /**
   * Heading field in *ItemsMatrix → With Rich Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.withRichText.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Tiles field in *ItemsMatrix → With Rich Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_matrix.withRichText.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tiles: prismic.GroupField<
    Simplify<ItemsMatrixSliceWithRichTextPrimaryTilesItem>
  >;
}

/**
 * With Rich Text variation for ItemsMatrix Slice
 *
 * - **API ID**: `withRichText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ItemsMatrixSliceWithRichText = prismic.SharedSliceVariation<
  "withRichText",
  Simplify<ItemsMatrixSliceWithRichTextPrimary>,
  never
>;

/**
 * Slice variation for *ItemsMatrix*
 */
type ItemsMatrixSliceVariation =
  | ItemsMatrixSliceDefault
  | ItemsMatrixSliceWithRichText;

/**
 * ItemsMatrix Shared Slice
 *
 * - **API ID**: `items_matrix`
 * - **Description**: ItemsMatrix
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ItemsMatrixSlice = prismic.SharedSlice<
  "items_matrix",
  ItemsMatrixSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SimpleTextSection → Default → Primary*
 */
export interface SimpleTextSectionSliceDefaultPrimary {
  /**
   * Text field in *SimpleTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Background field in *SimpleTextSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text_section.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background: prismic.ImageField<never>;

  /**
   * Background Color field in *SimpleTextSection → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_text_section.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for SimpleTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleTextSection*
 */
type SimpleTextSectionSliceVariation = SimpleTextSectionSliceDefault;

/**
 * SimpleTextSection Shared Slice
 *
 * - **API ID**: `simple_text_section`
 * - **Description**: SimpleTextSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleTextSectionSlice = prismic.SharedSlice<
  "simple_text_section",
  SimpleTextSectionSliceVariation
>;

/**
 * Item in *Timeline → Default → Primary → steps*
 */
export interface TimelineSliceDefaultPrimaryStepsItem {
  /**
   * content field in *Timeline → Default → Primary → steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.default.primary.steps[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * image field in *Timeline → Default → Primary → steps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.default.primary.steps[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Timeline → Default → Primary*
 */
export interface TimelineSliceDefaultPrimary {
  /**
   * steps field in *Timeline → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<Simplify<TimelineSliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for Timeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimelineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Timeline*
 */
type TimelineSliceVariation = TimelineSliceDefault;

/**
 * Timeline Shared Slice
 *
 * - **API ID**: `timeline`
 * - **Description**: Timeline
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineSlice = prismic.SharedSlice<
  "timeline",
  TimelineSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavDocument,
      NavDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CardsSlice,
      CardsSliceDefaultPrimaryCardsItem,
      CardsSliceDefaultPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ItemsMatrixSlice,
      ItemsMatrixSliceDefaultPrimaryTilesItem,
      ItemsMatrixSliceDefaultPrimary,
      ItemsMatrixSliceWithRichTextPrimaryTilesItem,
      ItemsMatrixSliceWithRichTextPrimary,
      ItemsMatrixSliceVariation,
      ItemsMatrixSliceDefault,
      ItemsMatrixSliceWithRichText,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SimpleTextSectionSlice,
      SimpleTextSectionSliceDefaultPrimary,
      SimpleTextSectionSliceVariation,
      SimpleTextSectionSliceDefault,
      TimelineSlice,
      TimelineSliceDefaultPrimaryStepsItem,
      TimelineSliceDefaultPrimary,
      TimelineSliceVariation,
      TimelineSliceDefault,
    };
  }
}
