// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  items_matrix: defineAsyncComponent(() => import("./ItemsMatrix/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  simple_text_section: defineAsyncComponent(
    () => import("./SimpleTextSection/index.vue"),
  ),
});
